### ISSUE TITLE
Deploy 1.3

### ISSUE THREAD

**Issue by capasfield** [di2ag/Connections-Hypothesis-Provider-Roadmap#89]
https://arax.ncats.io/?smartapi=1 shows that Connections Hypothesis Provider API has 1.2 in development (infores:connections-hypothesis).

Please deploy 1.3 of this tool into development ASAP.

**Comment by capasfield** [comment]
@GregHydeDartmouth Tagging you for visibility.

**Comment by GregHydeDartmouth** [comment]
@capasfield We've updated our smartapi yaml file to reflect our trapi 1.3 endpoint. Please see here: https://arax.ncats.io/?smartapi=1. 

I will close the ticket, but if this is not sufficient, feel free to reopen.
